#!/bin/busybox sh

/bin/busybox --install

mount -t proc proc /proc
mount -t sysfs none /sys
mount -t devfs devfs /dev

mdev -s

mkdir -p /etc/network
cat > /etc/network/interfaces << "EOF"
auto eth0
iface eth0 inet dhcp
EOF

mkdir -p /usr/share/udhcpc/

cat > /usr/share/udhcpc/default.script << "EOF"
#!/bin/sh
# udhcpc Interface Configuration
# Based on http://lists.debian.org/debian-boot/2002/11/msg00500.html
# udhcpc script edited by Tim Riker <Tim@Rikers.org>

[ -z "$1" ] && echo "Error: should be called from udhcpc" && exit 1

RESOLV_CONF="/etc/resolv.conf"
[ -n "$broadcast" ] && BROADCAST="broadcast $broadcast"
[ -n "$subnet" ] && NETMASK="netmask $subnet"

case "$1" in
        deconfig)
                /sbin/ifconfig $interface 0.0.0.0
                ;;

        renew|bound)
                /sbin/ifconfig $interface $ip $BROADCAST $NETMASK

                if [ -n "$router" ] ; then
                        while route del default gw 0.0.0.0 dev $interface ; do
                                true
                        done

                        for i in $router ; do
                                route add default gw $i dev $interface
                        done
                fi

                echo -n > $RESOLV_CONF
                [ -n "$domain" ] && echo search $domain >> $RESOLV_CONF
                for i in $dns ; do
                        echo nameserver $i >> $RESOLV_CONF
                done
                ;;
esac

exit 0
EOF

chmod +x /usr/share/udhcpc/default.script

ifconfig eth0 up
udhcpc -i eth0

#exec /bin/busybox sh
exec /app
#exec switch_root /mnt/rootfs /sbin/init
